name: PortfolioPipeline

on:
  push:
    branches: [main]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Install Dependecies
        run: |
          echo "Running Installing Dependencies..."
          yarn install
      - name: Run Linting
        run: |
          echo "Running Linting tests..."
          yarn run lint
        env:
          CI: true
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lintTest]
    steps:
      - name: Deployment
        run: |
          echo "Deployment in Progress..."
          yarn run build --if-present
